"""Add board tables

Revision ID: d01b9c777f11
Revises: 6c426a5bd568
Create Date: 2026-01-05 06:26:24.804243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01b9c777f11'
down_revision: Union[str, Sequence[str], None] = '6c426a5bd568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_posts_id'), 'board_posts', ['id'], unique=False)
    op.create_index(op.f('ix_board_posts_title'), 'board_posts', ['title'], unique=False)
    op.create_table('board_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['board_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_comments_id'), 'board_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_comments_id'), table_name='board_comments')
    op.drop_table('board_comments')
    op.drop_index(op.f('ix_board_posts_title'), table_name='board_posts')
    op.drop_index(op.f('ix_board_posts_id'), table_name='board_posts')
    op.drop_table('board_posts')
    # ### end Alembic commands ###
