import sys
import os
import math
import random

sys.path.append(os.path.abspath("build/src"))

try:
    import FinancialEngine as fe
except ImportError as e:
    print(f"[Error] Failed to load C++ Core: {e}")
    sys.exit(1)

def generate_synthetic_market(steps=200, base_price=100.0, amplitude=10.0):
    """
    Generates a highly volatile, range-bound market (Sine wave + Noise)
    Perfect for demonstrating Gamma Scalping (buying low, selling high).
    """
    prices = []
    for i in range(steps):
        # Sine wave oscillating between 90 and 110, plus some random market noise
        noise = random.uniform(-1.0, 1.0)
        price = base_price + amplitude * math.sin(i / 10.0) + noise
        prices.append(price)
    return prices

def run_gamma_scalping_simulation():
    print("\n=======================================================")
    print(" ⚡ GAMMA SCALPING SIMULATION (DYNAMIC DELTA HEDGING)")
    print("=======================================================")
    
    # 1. Generate Synthetic Data
    # 200 ticks of a highly volatile market bouncing around $100
    print("  [Data] Generating highly volatile synthetic market data...")
    prices = generate_synthetic_market()
    
    # 2. Initialize Engine
    # Starting Capital: $100,000, Strategy: GAMMA, Leverage: 1.0
    initial_capital = 100000.0
    engine = fe.Backtester(initial_capital, "GAMMA", 1.0)
    engine.set_regime_filter(False) # Turn off regime filter for pure mechanics test
    
    print("  [System] Feeding ticks to C++ Dynamic Delta Hedger...")
    
    # 3. Market Data Loop
    for i, price in enumerate(prices):
        timestamp = float(i)
        engine.on_market_data("SYNTH", timestamp, price, price, price, price)
        
    # 4. Results Extraction
    equity = engine.get_total_equity()
    trades = engine.get_trade_history()
    
    # In this simulation, the engine only trades the UNDERLYING stock to hedge the implied option.
    # Therefore, the PnL strictly represents the "Hedging Profit" generated by Gamma.
    gross_profit = equity - initial_capital
    
    print("\n=======================================================")
    print(" 📊 GAMMA SCALPING PERFORMANCE REPORT")
    print("=======================================================")
    print(f"  > Initial Capital:  ${initial_capital:,.2f}")
    print(f"  > Final Equity:     ${equity:,.2f}")
    print(f"  > Scalping Profit:  +${gross_profit:,.2f}")
    print(f"  > Total Trades:     {len(trades)}")
    print("=======================================================")
    print("  💡 How it works:")
    print("  As price rises, Delta increases -> Engine SELLS stock (Sell High).")
    print("  As price falls, Delta decreases -> Engine BUYS stock (Buy Low).")
    print("  This mechanical 'buy low, sell high' captures volatility!")
    print("=======================================================\n")

if __name__ == "__main__":
    run_gamma_scalping_simulation()